(()=>{'use strict';
/* Configure only after deploying matching, authenticated server routes. Defaults intentionally disabled. */
const ADMIN_API={enabled:false,baseUrl:'',routes:{auth:null,list:null,upload:null,create:null,delete:null},headers:{}};
const categories={sun:'خورشیدی',monk:'راهب','green-cheek':'گرین‌چیک'};
const LOGIN_CODE='mohamadreza8340'; // NOT SECURE FOR PRODUCTION: visible in client-side source. Replace with server-side authentication.
const $=id=>document.getElementById(id),notice=$('adminNotice'),loginCard=$('loginCard'),dashboard=$('dashboard');let previewUrl='';
function message(textValue,type='warning'){notice.hidden=false;notice.className='notice '+type;notice.textContent=textValue}
function routesReady(){return ADMIN_API.enabled&&ADMIN_API.baseUrl&&Object.values(ADMIN_API.routes).every(Boolean)}
function routeUrl(key){return ADMIN_API.baseUrl.replace(/\/$/,'')+ADMIN_API.routes[key]}
$('loginButton').addEventListener('click',()=>{if($('adminCode').value!==LOGIN_CODE){$('loginError').hidden=false;return}$('loginError').hidden=true;loginCard.hidden=true;dashboard.hidden=false;if(!routesReady())message('ورود نمایشی انجام شد، اما مسیرهای مدیریتی سرور پیکربندی نشده‌اند؛ ثبت، حذف و فهرست‌گیری غیرفعال است. کد ورود سمت کاربر امن نیست.');else{message('ورود نمایشی؛ برای احراز هویت واقعی، مسیر auth سرور را پیاده کنید.', 'warning');loadList()}});
$('adminCode').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginButton').click()});
$('imageFile').addEventListener('change',()=>{const file=$('imageFile').files[0],img=$('imagePreview'),box=$('previewBox');if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=''}if(!file){img.hidden=true;box.querySelector('span').hidden=false;$('fileInfo').textContent='';return}if(!file.type.startsWith('image/')){message('فایل انتخابی تصویر معتبر نیست.');$('imageFile').value='';return}previewUrl=URL.createObjectURL(file);img.src=previewUrl;img.hidden=false;box.querySelector('span').hidden=true;$('fileInfo').textContent=file.name+' · '+(file.size/1024/1024).toFixed(2)+' مگابایت';message('پیش‌نمایش محلی آماده است؛ این فایل هنوز به سرور ارسال یا در مرورگر ذخیره نشده است.','success')});
async function request(url,options={}){const res=await fetch(url,{...options,headers:{...ADMIN_API.headers,...options.headers}});if(!res.ok)throw new Error('HTTP '+res.status);return res.status===204?null:res.json()}
async function loadList(){const list=$('adminList');if(!routesReady()){list.textContent='مسیر فهرست ادمین پیکربندی نشده است.';return}try{const payload=await request(routeUrl('list')),items=Array.isArray(payload)?payload:(payload&&(payload.data||payload.items||payload.products)||[]);list.replaceChildren();if(!items.length){list.textContent='موردی ثبت نشده است.';return}for(const item of items){const row=document.createElement('div');row.className='admin-row';const info=document.createElement('span');info.textContent=(item.name||item.title||'بدون عنوان')+' · '+(categories[item.category]||item.category||'بدون دسته');const del=document.createElement('button');del.type='button';del.className='outline-button';del.textContent='حذف';del.addEventListener('click',async()=>{if(!item.id||!confirm('این تصویر از سرور حذف شود؟'))return;try{const url=routeUrl('delete').replace('{id}',encodeURIComponent(item.id));await request(url,{method:'DELETE',headers:{Authorization:'Bearer '+(sessionStorage.getItem('totiAdminToken')||'')}});message('حذف از سرور انجام شد.','success');await loadList()}catch(err){message('حذف ناموفق بود: '+err.message)}});row.append(info,del);list.append(row)}}catch(e){list.textContent='دریافت فهرست ناموفق بود؛ شبکه یا پیکربندی مسیر را بررسی کنید.';message('خطا در دریافت فهرست از سرور: '+e.message)}}
$('productForm').addEventListener('submit',async e=>{e.preventDefault();if(!routesReady()){message('عکس فقط پیش‌نمایش شده است؛ مسیرهای مدیریتی backend پیکربندی نشده‌اند و چیزی ثبت/بارگذاری نشد.');return}const file=$('imageFile').files[0];if(!file){message('ابتدا فایل تصویر انتخاب کنید.');return}try{const auth=await request(routeUrl('auth'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('adminCode').value})});if(!auth||!auth.token)throw new Error('توکن احراز هویت در پاسخ auth موجود نیست');const headers={Authorization:'Bearer '+auth.token};sessionStorage.setItem('totiAdminToken',auth.token);const form=new FormData();form.append('file',file);const uploaded=await request(routeUrl('upload'),{method:'POST',headers,body:form});if(!uploaded||!uploaded.url)throw new Error('آدرس url در پاسخ upload موجود نیست');const result=await request(routeUrl('create'),{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({name:$('pName').value.trim(),category:$('pCategory').value,price:$('pPrice').value.trim(),description:$('pDesc').value.trim(),image_url:uploaded.url})});message('پاسخ ثبت از سرور دریافت شد.','success');$('productForm').reset();$('imagePreview').hidden=true;$('previewBox').querySelector('span').hidden=false;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';$('fileInfo').textContent='';await loadList()}catch(err){message('ثبت انجام نشد یا پاسخ سرور با قرارداد مورد انتظار سازگار نیست: '+err.message)}});
window.addEventListener('beforeunload',()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)});
})();