(()=>{'use strict';
const API='https://toti-ara-gallery.mohammadrezasamieizadeh.workers.dev/api/gallery';
const categories={sun:'خورشیدی',monk:'راهب','green-cheek':'گرین‌چیک'};
const state={items:[],filter:'all'};const grid=document.getElementById('galleryGrid'),status=document.getElementById('galleryStatus'),retry=document.getElementById('retryGallery');
function pick(obj,...keys){for(const k of keys)if(obj&&obj[k]!=null)return obj[k];return ''}
function normalize(payload){const list=Array.isArray(payload)?payload:(payload&&Array.isArray(payload.data)?payload.data:(payload&&Array.isArray(payload.products)?payload.products:(payload&&Array.isArray(payload.items)?payload.items:[])));return list.map((p,i)=>({id:pick(p,'id')||i,name:String(pick(p,'name','title')||'پرنده طوطی آرا'),category:String(pick(p,'category','type')||''),price:String(pick(p,'price','status')||''),description:String(pick(p,'description','desc')||''),image:String(pick(p,'image_url','imageUrl','image','url','photo_url')||'')})).filter(x=>x.image)}
function text(el,value){el.textContent=value}
function render(){const items=state.items.filter(x=>state.filter==='all'||x.category===state.filter);grid.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='empty-state';text(e,state.items.length?'در این دسته تصویری ثبت نشده است.':'هنوز تصویری برای نمایش وجود ندارد.');grid.append(e);return}for(const item of items){const article=document.createElement('article');article.className='bird-card';const img=document.createElement('img');img.src=item.image;img.alt=item.name;img.loading='lazy';img.onerror=()=>{img.alt='بارگذاری تصویر ناموفق بود';img.removeAttribute('src')};const body=document.createElement('div');body.className='bird-card-body';const title=document.createElement('h3');text(title,item.name);body.append(title);if(item.price||item.description){const p=document.createElement('p');text(p,[item.price,item.description].filter(Boolean).join(' · '));body.append(p)}if(categories[item.category]){const tag=document.createElement('span');tag.className='card-category';text(tag,categories[item.category]);body.append(tag)}article.append(img,body);grid.append(article)}}
async function load(){status.className='notice';text(status,'در حال دریافت گالری…');retry.hidden=true;try{const response=await fetch(API,{method:'GET',headers:{Accept:'application/json'},mode:'cors',cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const payload=await response.json();state.items=normalize(payload);render();status.hidden=state.items.length>0;if(!state.items.length){status.hidden=false;text(status,'اتصال برقرار شد، اما هنوز عکسی از سرور دریافت نشد.');}}catch(err){state.items=[];render();status.hidden=false;status.className='notice error';text(status,'دریافت عکس‌ها ناموفق بود. اتصال اینترنت، پاسخ سرور و دسترسی CORS را بررسی کنید؛ می‌توانید دوباره تلاش کنید.');retry.hidden=false;console.warn('Gallery request failed:',err)}}
document.querySelectorAll('.filter-pill').forEach(btn=>btn.addEventListener('click',()=>{state.filter=btn.dataset.category;document.querySelectorAll('.filter-pill').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});render()}));retry.addEventListener('click',load);load();
// Small pure helpers are exposed for fixture-based checks without changing live behavior.
window.TotiGallery={normalize,filter:(items,category)=>items.filter(x=>category==='all'||x.category===category),categories};})();