-- طوطی آرا: جداول، داده اولیه و قوانین امنیتی Supabase

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price text default '',
  image_url text default '',
  emoji text default '🦜',
  available boolean default true,
  created_at timestamptz default now()
);

alter table public.products enable row level security;

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products
  for select to anon, authenticated using (true);

drop policy if exists "authenticated insert products" on public.products;
create policy "authenticated insert products" on public.products
  for insert to authenticated with check (true);

drop policy if exists "authenticated update products" on public.products;
create policy "authenticated update products" on public.products
  for update to authenticated using (true) with check (true);

drop policy if exists "authenticated delete products" on public.products;
create policy "authenticated delete products" on public.products
  for delete to authenticated using (true);

create table if not exists public.site_sections (
  slug text primary key,
  title text not null,
  body text default '',
  published boolean default true,
  updated_at timestamptz default now()
);
alter table public.site_sections enable row level security;
drop policy if exists "public read site sections" on public.site_sections;
create policy "public read site sections" on public.site_sections for select to anon, authenticated using (published = true);
drop policy if exists "authenticated manage site sections" on public.site_sections;
create policy "authenticated manage site sections" on public.site_sections for all to authenticated using (true) with check (true);
insert into public.site_sections (slug,title,body) values
('about','About','ما در طوطی آرا انتخاب یک هم‌نشین دوست‌داشتنی را با اطلاعات درست و پشتیبانی واقعی همراه می‌کنیم.'),
('gallery','Gallery','تصاویر سالن و پرندگان را برای آشنایی بیشتر ببینید.'),
('care','Care Tips','راهنمای تغذیه، بهداشت و نگهداری پرندگان را از کارشناسان دریافت کنید.'),
('contact','Contact Us','برای انتخاب پرنده، ثبت سفارش و پرسش‌های نگهداری با ما در تماس باشید.')
on conflict (slug) do nothing;

create table if not exists public.site_settings (
  id text primary key default 'singleton',
  site_name text default 'طوطی آرا',
  phone text default '09107488013',
  whatsapp text default '989107488013',
  address text default 'قزوین، مینودر',
  hero_title text default 'همراه کوچک شما، با عشق بزرگ می‌شود',
  hero_text text default 'طوطی آرا مجموعه‌ای از طوطی‌های سالم و اجتماعی را با مشاوره پیش از خرید و پشتیبانی پس از آن ارائه می‌کند.',
  hero_image_url text default 'hero.png',
  feature_1 text default 'سلامت تضمینی',
  feature_2 text default 'تخم و جوجه',
  feature_3 text default 'مشاوره پیش از خرید',
  feature_4 text default 'پشتیبانی پس از فروش',
  updated_at timestamptz default now()
);

alter table public.site_settings enable row level security;

drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings" on public.site_settings
  for select to anon, authenticated using (id = 'singleton');

drop policy if exists "authenticated insert site settings" on public.site_settings;
create policy "authenticated insert site settings" on public.site_settings
  for insert to authenticated with check (id = 'singleton');

drop policy if exists "authenticated update site settings" on public.site_settings;
create policy "authenticated update site settings" on public.site_settings
  for update to authenticated using (id = 'singleton') with check (id = 'singleton');

insert into public.site_settings (id, site_name, phone, whatsapp, address, hero_title, hero_text, hero_image_url, feature_1, feature_2, feature_3, feature_4)
values ('singleton', 'طوطی آرا', '09107488013', '989107488013', 'قزوین، مینودر', 'همراه کوچک شما، با عشق بزرگ می‌شود', 'طوطی آرا مجموعه‌ای از طوطی‌های سالم و اجتماعی را با مشاوره پیش از خرید و پشتیبانی پس از آن ارائه می‌کند.', 'hero.png', 'سلامت تضمینی', 'تخم و جوجه', 'مشاوره پیش از خرید', 'پشتیبانی پس از فروش')
on conflict (id) do nothing;

insert into public.products (name, description, emoji)
select 'خورشیدی', 'رنگ فوق‌العاده زیبا • باهوش و اجتماعی • سرزنده و بازیگوش', '☀️'
where not exists (select 1 from public.products where name = 'خورشیدی');
insert into public.products (name, description, emoji)
select 'راهب', 'باهوش و تربیت‌پذیر • صدای ملایم • مناسب هم‌نشینی', '🦜'
where not exists (select 1 from public.products where name = 'راهب');
insert into public.products (name, description, emoji)
select 'گرین‌چیک', 'مهربان و بازیگوش • رنگ‌های متنوع • اندازه مناسب', '🦜'
where not exists (select 1 from public.products where name = 'گرین‌چیک');

-- ساخت bucketهای عمومی برای URLهای قابل نمایش در سایت.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true), ('site-assets', 'site-assets', true)
on conflict (id) do update set public = excluded.public;

 drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects
  for select to anon, authenticated using (bucket_id = 'product-images');

drop policy if exists "authenticated upload product images" on storage.objects;
create policy "authenticated upload product images" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images');

drop policy if exists "authenticated update product images" on storage.objects;
create policy "authenticated update product images" on storage.objects
  for update to authenticated using (bucket_id = 'product-images') with check (bucket_id = 'product-images');

drop policy if exists "authenticated delete product images" on storage.objects;
create policy "authenticated delete product images" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images');

drop policy if exists "public read site assets" on storage.objects;
create policy "public read site assets" on storage.objects
  for select to anon, authenticated using (bucket_id = 'site-assets');

drop policy if exists "authenticated upload site assets" on storage.objects;
create policy "authenticated upload site assets" on storage.objects
  for insert to authenticated with check (bucket_id = 'site-assets');

drop policy if exists "authenticated update site assets" on storage.objects;
create policy "authenticated update site assets" on storage.objects
  for update to authenticated using (bucket_id = 'site-assets') with check (bucket_id = 'site-assets');

drop policy if exists "authenticated delete site assets" on storage.objects;
create policy "authenticated delete site assets" on storage.objects
  for delete to authenticated using (bucket_id = 'site-assets');


-- Optional image catalog keeps uploaded product images selectable in the owner panel.
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  storage_path text not null unique,
  public_url text not null,
  alt_text text default '',
  created_at timestamptz default now()
);
alter table public.product_images enable row level security;
drop policy if exists "public read product image catalog" on public.product_images;
create policy "public read product image catalog" on public.product_images
  for select to anon, authenticated using (true);
drop policy if exists "authenticated manage product image catalog" on public.product_images;
create policy "authenticated manage product image catalog" on public.product_images
  for all to authenticated using (true) with check (true);

-- Existing products remain intact; image_url remains the backwards-compatible primary image field.
