-- طوطی آرا: ساخت جدول محصولات و قوانین امنیتی
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price text default '',
  image_url text default '',
  emoji text default '🦜',
  available boolean default true,
  created_at timestamptz default now()
);

alter table public.products enable row level security;

-- همه بازدیدکنندگان می‌توانند محصولات موجود را ببینند.
drop policy if exists "public read products" on public.products;
create policy "public read products"
on public.products for select
to anon, authenticated
using (true);

-- فقط کاربران واردشده می‌توانند محصول اضافه/ویرایش/حذف کنند.
drop policy if exists "authenticated insert products" on public.products;
create policy "authenticated insert products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "authenticated update products" on public.products;
create policy "authenticated update products"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete products" on public.products;
create policy "authenticated delete products"
on public.products for delete
to authenticated
using (true);

-- سه محصول اولیه
insert into public.products (name, description, emoji)
select 'خورشیدی','رنگ فوق‌العاده زیبا • باهوش و اجتماعی • سرزنده و بازیگوش','☀️'
where not exists (select 1 from public.products where name='خورشیدی');

insert into public.products (name, description, emoji)
select 'راهب','باهوش و تربیت‌پذیر • صدای ملایم • مناسب هم‌نشینی','🦜'
where not exists (select 1 from public.products where name='راهب');

insert into public.products (name, description, emoji)
select 'گرین‌چیک','مهربان و بازیگوش • رنگ‌های متنوع • اندازه مناسب','🦜'
where not exists (select 1 from public.products where name='گرین‌چیک');
